server:
  port: 8761

spring:
  application:
    name: REGISTRY-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bt-microservices

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
