server:
  port: 8086

spring:
  application:
    name: STUDENTS-CONNECT-SERVICE

eureka:
  instance:
    host: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.host}:8761/eureka
